
name: "Regenerate WhoAmI table"

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - 'whoami.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Needed to push changes
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
          enable-cache: true
          cache-dependency-glob: .github/workflows/gen-whoami-table.py

      - name: Run gen-whoami-table.py
        run: |
          uv run .github/workflows/gen-whoami-table.py ./whoami.yml

      - name: Output generated table to actions summary
        run: |
          cat whoami.md >> $GITHUB_STEP_SUMMARY

      - name: Commit changes
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add whoami.md
          if ! git diff --cached --quiet; then
            git commit -m "Update device WhoAmI table"
            git push
          else
            echo "No changes to commit."
          fi
